# Generated by Django 4.0.5 on 2022-06-22 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('idProcedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('totalActividades', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=1)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicial')),
                ('dias', models.PositiveIntegerField()),
                ('fechaFin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Final')),
                ('jerarquia', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('activo', models.BooleanField(default=1)),
                ('idProcedimientoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.procedimientos')),
            ],
        ),
    ]
