# Generated by Django 4.0.5 on 2022-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
