# Generated by Django 4.0.5 on 2022-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_procedimientos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='completa',
            field=models.BooleanField(default=0),
        ),
    ]
